apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  SERVER_PORT: "8083"
  SPRING_APPLICATION_NAME: "notification-service"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-broker.default.svc.cluster.local:29092"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,metrics,prometheus"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: notification-service-config

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: notification-service
