apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
stringData:
  SPRING_DATA_MONGODB_URI: "mongodb://root:1234@mongodb-product.default.svc.cluster.local:27017/product-service?authSource=admin"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: "product-service"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,metrics,prometheus"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: product-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secret

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: product-service
